name: Trigger auto deployment for frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/frontend-AutoDeployTrigger-842cef05-b28c-4113-8d6e-21161a367fb7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: patricktestacr.azurecr.io
          username: ${{ secrets.FRONTEND_REGISTRY_USERNAME }}
          password: ${{ secrets.FRONTEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: patricktestacr.azurecr.io/frontend:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FRONTEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n frontend -g patricktest --server patricktestacr.azurecr.io --username  ${{ secrets.FRONTEND_REGISTRY_USERNAME }} --password ${{ secrets.FRONTEND_REGISTRY_PASSWORD }}
            az containerapp update -n frontend -g patricktest --image patricktestacr.azurecr.io/frontend:${{ github.sha }}
